WITH RES01 AS(
		SELECT  CASE  WHEN UPPER(T1.DATA_TYPE) = 'INT' THEN 'INT'
					  WHEN UPPER(T1.DATA_TYPE) = 'TINYINT' THEN 'TINYINT'
					  WHEN UPPER(T1.DATA_TYPE) = 'SMALLINT' THEN 'SMALLINT'
					  WHEN UPPER(T1.DATA_TYPE) = 'BIGINT' THEN 'BIGINT'
					  WHEN UPPER(T1.DATA_TYPE) = 'BIT' THEN 'TINYINT'
					  WHEN UPPER(T1.DATA_TYPE) = 'FLOAT' THEN 'FLOAT'
					  WHEN UPPER(T1.DATA_TYPE) IN ('NUMERIC','DECIMAL','MONEY','SMALLMONEY') THEN 'DECIMAL'
					  WHEN UPPER(T1.DATA_TYPE) IN ('CHAR','NCHAR') THEN 'CHAR'
					  WHEN UPPER(T1.DATA_TYPE) IN ('VARCHAR','NVARCHAR') THEN 'VARCHAR'
					  WHEN UPPER(T1.DATA_TYPE) = 'DATE' THEN 'DATE'
					  WHEN UPPER(T1.DATA_TYPE) IN ('DATETIME','DATETIME2') THEN 'DATETIME(6)'
					  WHEN UPPER(T1.DATA_TYPE) IN ('SMALLDATETIME','DATETIMEOFFSET') THEN 'DATETIME'
					  WHEN UPPER(T1.DATA_TYPE) IN ('TIMESTAMP','ROWVERSION') THEN 'TIMESTAMP'
					  WHEN UPPER(T1.DATA_TYPE) IN ('BINARY') THEN 'BINARY'
					  WHEN UPPER(T1.DATA_TYPE) IN ('VARBINARY') THEN 'LONGBLOB'
					  WHEN UPPER(T1.DATA_TYPE) IN ('TEXT','NTEXT') THEN 'TEXT'
					  WHEN UPPER(T1.DATA_TYPE) = 'IMAGE' THEN 'LONGBLOB'
					  WHEN UPPER(T1.DATA_TYPE) = 'XML' THEN 'TEXT'
				END NEW_DTP
				,CASE WHEN T1.CHARACTER_MAXIMUM_LENGTH IS NOT NULL AND T1.CHARACTER_MAXIMUM_LENGTH >= 1 THEN '('+CONVERT(VARCHAR,T1.CHARACTER_MAXIMUM_LENGTH)+')' END CHR_LEN
				,CASE WHEN T1.NUMERIC_PRECISION IS NOT NULL AND ISNULL(T1.NUMERIC_SCALE,0) > 0
							THEN '('+ CONVERT(VARCHAR,T1.NUMERIC_PRECISION) +','+CONVERT(VARCHAR,T1.NUMERIC_SCALE)+')'
					  WHEN T1.NUMERIC_PRECISION IS NOT NULL AND ISNULL(T1.NUMERIC_SCALE,0) = 0
					        THEN '('+ CONVERT(VARCHAR,T1.NUMERIC_PRECISION) + ')'  END NUM_LEN
				,(	SELECT X.VALUE
					FROM (
					SELECT OBJTYPE, OBJNAME, NAME, VALUE FROM ::FN_LISTEXTENDEDPROPERTY(NULL, 'SCHEMA', T1.TABLE_SCHEMA, 'TABLE', T1.TABLE_NAME, 'COLUMN', DEFAULT)
					) X WHERE X.OBJNAME COLLATE DATABASE_DEFAULT = T1.COLUMN_NAME COLLATE DATABASE_DEFAULT
				) COL_CMT
				,COLUMNPROPERTY(object_id(TABLE_SCHEMA+'.'+TABLE_NAME), COLUMN_NAME, 'IsIdentity') IS_IDENTITY
				,T1.*
		FROM    INFORMATION_SCHEMA.COLUMNS T1
		WHERE   T1.TABLE_CATALOG = '{0}'
		AND     T1.TABLE_NAME = '{1}'
		-- ORDER BY T1.ORDINAL_POSITION
		)
,RES02 AS(
		--PK 15개까지만 처리
		SELECT  T1.TABLE_NAME
				,MAX(CASE WHEN T2.ORDINAL_POSITION = 1 THEN ',PRIMARY KEY(' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 2 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 3 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 4 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 5 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 6 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 7 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 8 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 9 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 10 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 11 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 12 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 13 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 14 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 15 THEN ',' + T2.COLUMN_NAME ELSE '' END) +
				 MAX(CASE WHEN T2.ORDINAL_POSITION = 1 THEN ')' ELSE '' END) PK_STR
				 ,T1.TABLE_CATALOG
				 ,T1.TABLE_SCHEMA
				 ,(SELECT VALUE FROM ::FN_LISTEXTENDEDPROPERTY(NULL, 'SCHEMA', T1.TABLE_SCHEMA, 'TABLE', T1.TABLE_NAME, DEFAULT, DEFAULT)) TAB_CMT
		FROM    INFORMATION_SCHEMA.TABLES T1
		        LEFT OUTER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE T2
				  ON (T2.TABLE_CATALOG = T1.TABLE_CATALOG
				      AND T2.TABLE_SCHEMA = T1.TABLE_SCHEMA
					  AND T2.TABLE_NAME = T1.TABLE_NAME)
		WHERE   T1.TABLE_CATALOG = '{2}'
		AND     T1.TABLE_NAME = '{3}'
		GROUP BY T1.TABLE_CATALOG ,T1.TABLE_SCHEMA ,T1.TABLE_NAME
		)
SELECT  T3.DDL_STR
FROM    (
		SELECT  CHAR(9)
		        + CASE WHEN T1.ORDINAL_POSITION = 1 THEN T1.COLUMN_NAME ELSE ',' + T1.COLUMN_NAME END
				+' '+T1.NEW_DTP + ' '
					+ CASE WHEN T1.CHR_LEN IS NOT NULL THEN T1.CHR_LEN
						   WHEN T1.NUM_LEN IS NOT NULL THEN T1.NUM_LEN
						   ELSE '' END
				+' '+CASE WHEN T1.IS_NULLABLE = 'YES' THEN 'NULL' ELSE 'NOT NULL' END
				+CASE WHEN T1.IS_IDENTITY = 1 THEN ' AUTO_INCREMENT ' ELSE '' END
				+' '+CASE WHEN T1.COL_CMT IS NOT NULL THEN ' COMMENT ''' + CAST(T1.COL_CMT AS VARCHAR) + '''' ELSE '' END
				DDL_STR
				,T1.TABLE_CATALOG
				,T1.TABLE_SCHEMA
				,T1.TABLE_NAME
				,T1.ORDINAL_POSITION
				,T1.COLUMN_NAME
				,T1.DATA_TYPE
				,T1.CHARACTER_MAXIMUM_LENGTH
				,T1.CHARACTER_OCTET_LENGTH
				,T1.NUMERIC_PRECISION
				,T1.NUMERIC_SCALE
				,T1.COLLATION_NAME
		FROM    RES01 T1
		UNION ALL
		SELECT  'CREATE TABLE {4}.' + T1.TABLE_NAME +  ' (' DDL_STR
				,T1.TABLE_CATALOG
				,T1.TABLE_SCHEMA
				,T1.TABLE_NAME
				,0 ORDINAL_POSITION
				,NULL COLUMN_NAME
				,NULL DATA_TYPE
				,NULL CHARACTER_MAXIMUM_LENGTH
				,NULL CHARACTER_OCTET_LENGTH
				,NULL NUMERIC_PRECISION
				,NULL NUMERIC_SCALE
				,NULL COLLATION_NAME
		FROM    RES02 T1
		UNION ALL
		SELECT  char(9) + T1.PK_STR DDL_STR
				,T1.TABLE_CATALOG
				,T1.TABLE_SCHEMA
				,T1.TABLE_NAME
				,99990 ORDINAL_POSITION
				,NULL COLUMN_NAME
				,NULL DATA_TYPE
				,NULL CHARACTER_MAXIMUM_LENGTH
				,NULL CHARACTER_OCTET_LENGTH
				,NULL NUMERIC_PRECISION
				,NULL NUMERIC_SCALE
				,NULL COLLATION_NAME
		FROM    RES02 T1
		WHERE   T1.PK_STR != ''
		UNION ALL
		SELECT  ') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 '
				  + CASE WHEN T1.TAB_CMT IS NOT NULL THEN ' COMMENT ''' + CAST(T1.TAB_CMT AS VARCHAR)+ ''';' ELSE ';' END DDL_STR
				,T1.TABLE_CATALOG
				,T1.TABLE_SCHEMA
				,T1.TABLE_NAME
				,99991 ORDINAL_POSITION
				,NULL COLUMN_NAME
				,NULL DATA_TYPE
				,NULL CHARACTER_MAXIMUM_LENGTH
				,NULL CHARACTER_OCTET_LENGTH
				,NULL NUMERIC_PRECISION
				,NULL NUMERIC_SCALE
				,NULL COLLATION_NAME
		FROM    RES02 T1
		) T3
ORDER BY T3.TABLE_CATALOG ,T3.TABLE_SCHEMA, T3.TABLE_NAME ,T3.ORDINAL_POSITION


